name = "not-found-test"
compatibility_date = "2026-05-05"
compatibility_flags = ["nodejs_compat"]
main = "./server.ts"

[assets]
directory = "./build/client"
binding = "ASSETS"
run_worker_first = ["/assets/broken/*", "/assets/fixed/*"]

[build]
command = "pnpm run build"
