name = "not-found-test"
compatibility_date = "2026-05-05"
compatibility_flags = ["nodejs_compat"]
main = "./workers/app.ts"

[assets]
directory = "./build/client"
not_found_handling = "single-page-application"

[vars]
BUG_MODE = "broken"
